apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:  {{ include "dh-ms-docs.name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ include "dh-ms-docs.name" . }}
        tier: backend
        track: stable
    spec:
      containers:
        - name: {{ include "dh-ms-docs.name" . }}
          image: "{{ .Values.DockerRepo }}:{{ .Values.DockerTag }}"
          imagePullPolicy: Always
          args: ["server", "-b", "https://docs.deployhub.com", "--appendPort=false"] 
          ports:
            - containerPort: 1313     