apiVersion: v1
kind: Service
metadata:
  name: {{ include "dh-ms-docs.name" . }}
spec:
  selector:
    app: {{ include "dh-ms-docs.name" . }}
    tier: backend
  ports:
    - name: hugo
      port: 1313
  type: NodePort